import {
  Combine,
  FileText,
  FileSpreadsheet,
  Presentation,
  ImageIcon,
  Code2,
  FileCheck2,
  Type,
  PenLine,
  type LucideIcon,
} from "lucide-react";

export type ToolCategory = "convert" | "organize" | "edit";

export interface Tool {
  id: string;
  title: string;
  description: string;
  category: ToolCategory;
  implemented: boolean;
  href?: string;
  icon: LucideIcon;
  color: string;
}

export const tools: Tool[] = [
  {
    id: "merge-pdf",
    title: "Merge PDF",
    description: "Combine multiple PDF files into one document.",
    category: "organize",
    implemented: true,
    href: "/merge-pdf",
    icon: Combine,
    color: "bg-rose-100 text-rose-600 dark:bg-rose-950 dark:text-rose-400",
  },
  {
    id: "edit-pdf",
    title: "Edit PDF",
    description: "Add text, stamps, and signatures to a PDF.",
    category: "edit",
    implemented: true,
    href: "/edit-pdf",
    icon: PenLine,
    color: "bg-cyan-100 text-cyan-600 dark:bg-cyan-950 dark:text-cyan-400",
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Convert your PDF files into easy to edit DOC and DOCX documents.",
    category: "convert",
    implemented: true,
    href: "/pdf-to-word",
    icon: FileText,
    color: "bg-blue-100 text-blue-600 dark:bg-blue-950 dark:text-blue-400",
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Make DOC and DOCX files easy to read by converting them to PDF.",
    category: "convert",
    implemented: true,
    href: "/word-to-pdf",
    icon: FileText,
    color: "bg-blue-100 text-blue-600 dark:bg-blue-950 dark:text-blue-400",
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Pull data straight from PDFs into Excel spreadsheets in seconds.",
    category: "convert",
    implemented: true,
    href: "/pdf-to-excel",
    icon: FileSpreadsheet,
    color: "bg-emerald-100 text-emerald-600 dark:bg-emerald-950 dark:text-emerald-400",
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Make Excel spreadsheets easy to read by converting them to PDF.",
    category: "convert",
    implemented: true,
    href: "/excel-to-pdf",
    icon: FileSpreadsheet,
    color: "bg-emerald-100 text-emerald-600 dark:bg-emerald-950 dark:text-emerald-400",
  },
  {
    id: "pdf-to-powerpoint",
    title: "PDF to PowerPoint",
    description: "Turn your PDF files into easy to edit PPT and PPTX slideshows.",
    category: "convert",
    implemented: true,
    href: "/pdf-to-powerpoint",
    icon: Presentation,
    color: "bg-orange-100 text-orange-600 dark:bg-orange-950 dark:text-orange-400",
  },
  {
    id: "powerpoint-to-pdf",
    title: "PowerPoint to PDF",
    description: "Make PPT and PPTX slideshows easy to view by converting them to PDF.",
    category: "convert",
    implemented: true,
    href: "/powerpoint-to-pdf",
    icon: Presentation,
    color: "bg-orange-100 text-orange-600 dark:bg-orange-950 dark:text-orange-400",
  },
  {
    id: "pdf-to-jpg",
    title: "PDF to JPG",
    description: "Convert each PDF page into a JPG or extract all images in a PDF.",
    category: "convert",
    implemented: true,
    href: "/pdf-to-jpg",
    icon: ImageIcon,
    color: "bg-amber-100 text-amber-600 dark:bg-amber-950 dark:text-amber-400",
  },
  {
    id: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert JPG images to PDF in seconds. Adjust orientation and margins.",
    category: "convert",
    implemented: true,
    href: "/jpg-to-pdf",
    icon: ImageIcon,
    color: "bg-amber-100 text-amber-600 dark:bg-amber-950 dark:text-amber-400",
  },
  {
    id: "png-to-pdf",
    title: "PNG to PDF",
    description: "Convert PNG images to PDF in seconds, transparency included.",
    category: "convert",
    implemented: true,
    href: "/png-to-pdf",
    icon: ImageIcon,
    color: "bg-teal-100 text-teal-600 dark:bg-teal-950 dark:text-teal-400",
  },
  {
    id: "pdf-to-png",
    title: "PDF to PNG",
    description: "Convert each PDF page into a high-quality PNG image.",
    category: "convert",
    implemented: true,
    href: "/pdf-to-png",
    icon: ImageIcon,
    color: "bg-teal-100 text-teal-600 dark:bg-teal-950 dark:text-teal-400",
  },
  {
    id: "html-to-pdf",
    title: "HTML to PDF",
    description: "Convert webpages to PDF. Paste a URL and convert it with a click.",
    category: "convert",
    implemented: true,
    href: "/html-to-pdf",
    icon: Code2,
    color: "bg-violet-100 text-violet-600 dark:bg-violet-950 dark:text-violet-400",
  },
  {
    id: "pdf-to-text",
    title: "PDF to Text",
    description: "Extract plain text content from a PDF document.",
    category: "convert",
    implemented: true,
    href: "/pdf-to-text",
    icon: Type,
    color: "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300",
  },
  {
    id: "text-to-pdf",
    title: "Text to PDF",
    description: "Convert plain text files into a formatted PDF document.",
    category: "convert",
    implemented: true,
    href: "/text-to-pdf",
    icon: Type,
    color: "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300",
  },
  {
    id: "pdf-to-pdfa",
    title: "PDF to PDF/A",
    description: "Transform your PDF to PDF/A, the ISO-standard for long-term archiving.",
    category: "convert",
    implemented: true,
    href: "/pdf-to-pdfa",
    icon: FileCheck2,
    color: "bg-indigo-100 text-indigo-600 dark:bg-indigo-950 dark:text-indigo-400",
  },
];
